### PR TITLE
Add support for InputStreams, updated deprecated code

### PR DESCRIPTION
**Pull request by IvanDelsinne**
*From #16*

I implemented support for InputStreams in the FileUploader, but a question arise for me:
Wouldn't a FileUploader API redesign be better ?

There's a mess between 3 constructors, and a lot of unused private attributes, and I think that redesigning it to instead have some kind of helper/builder could help avoid that.
Something that'd build the Part or add itself to the built part instead of having a lot of constructors.

I also had to update the Maven target version to 1.6 since the 1.5 version was not supported anymore.

### CODE REVIEW

**Comment by dmitry-mukhin** [comment]
👍 great job

**Comment by dmitry-mukhin** [comment]
@IvanDelsinne can you add tests for new use case?

**Comment by IvanDelsinne** [comment]
I don't really know how to test this new feature, I'm gonna have to think about that.

**Comment by IvanDelsinne** [comment]
Thanks for your work

**Pull request merged**
